//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM4OARS.Models
{
    /*Author: Bertol Salgado 1361242
    * COSC 4351
    * Spring 2016
    * Added Data Notations
    */
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class View_Pending_Complaints
    {
        [Display(Name ="Complaint No")]   
        public int Complaint_No { get; set; }

        [Display(Name ="Apt No")]
        public int Apt_no { get; set; }

        [Display(Name = "Apt Type")]
        public Nullable<int> Apt_type { get; set; }

        [Display(Name = "Complaint Description")]
        public string Description_Complaint { get; set; }
    }
}
