//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM4OARS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRental
    {
        public int Tenant_SS { get; set; }
        public string Tenant_Name { get; set; }
        public Nullable<System.DateTime> Tenant_DOB { get; set; }
        public int Rental_No { get; set; }
        public Nullable<System.DateTime> Rental_Date { get; set; }
    }
}
