//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM4OARS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rental()
        {
            this.Complaints = new HashSet<Complaint>();
            this.Owns = new HashSet<Own>();
            this.Rental_Invoice = new HashSet<Rental_Invoice>();
        }
    
        public int Rental_No { get; set; }
        public Nullable<System.DateTime> Rental_Date { get; set; }
        public string Rental_Status { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string Lease_Type { get; set; }
        public Nullable<System.DateTime> Lease_Start { get; set; }
        public Nullable<System.DateTime> Lease_End { get; set; }
        public Nullable<System.DateTime> Renewal_Date { get; set; }
        public string Staff_number { get; set; }
        public Nullable<int> Apt_no { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Own> Owns { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental_Invoice> Rental_Invoice { get; set; }
    }
}
