//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM4OARS.Models
{
    /*Author: Bertol Salgado 1361242
    * COSC 4351
    * Spring 2016
    * Added Data Notations
    */
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class View_LeaseLength
    {
        [Display(Name ="Rental No")]
        public int Rental_No { get; set; }

        [Display(Name ="Start Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Lease_Start { get; set; }

        [Display(Name = "End Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Lease_End { get; set; }

        [Display(Name = "Length")]
        public Nullable<int> Lease_Length__Days_ { get; set; }
    }
}
