//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM4OARS.Models
{
    /*Author: Bertol Salgado 1361242
    * COSC 4351
    * Spring 2016
    * Added Data notations to Tenant Model Class
    */
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenant()
        {
            this.Owns = new HashSet<Own>();
            this.Tenant_Auto = new HashSet<Tenant_Auto>();
            this.Tenant_Family = new HashSet<Tenant_Family>();
            this.Testimonials = new HashSet<Testimonial>();
        }


        [Display(Name = "Tenant SSN")]
        [DisplayFormat(DataFormatString = "{0:###-##-####}")]
        [Required(ErrorMessage ="SSN is Required")]
        public int Tenant_SS { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string Tenant_Name { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "DOB is Required")]
        public Nullable<System.DateTime> Tenant_DOB { get; set; }

        [Display(Name = "Marital Status")]
        [Required(ErrorMessage = "Marital Status is Required")]
        public string Tenant_Marital { get; set; }

        [Display(Name = "Work Phone")]
        [DataType(DataType.PhoneNumber)]
        [DisplayFormat(DataFormatString = "{0:(###)-###-####}")]
        [Required(ErrorMessage = "Work Phone is Required")]
        public Nullable<long> Work_Phone { get; set; }

        [Display(Name = "Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [DisplayFormat(DataFormatString = "{0:(###)-###-####}")]
        [Required(ErrorMessage = "Home Phone is Required")]
        public Nullable<long> Home_Phone { get; set; }

        [Display(Name = "Employer")]
        [Required(ErrorMessage = "Employer is Required")]
        public string Employer { get; set; }

        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Gender Required")]
        public string Tenant_Gender { get; set; }

        [Display(Name = "Username")]
        [Required(ErrorMessage = "Username Required")]
        public string Tenant_Username { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is Required")]
        public string Tenant_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Own> Owns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenant_Auto> Tenant_Auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenant_Family> Tenant_Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testimonial> Testimonials { get; set; }
    }
}
