//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEAM4OARS.Models
{
    /*Author: Bertol Salgado 1361242
    * COSC 4351
    * Spring 2016
    * Added Data Notations
    */
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Testimonial
    {
        [Display(Name = "Testimonial ID")]
        public int Testimonial_ID { get; set; }

        [Display(Name = "Testimonial Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Testimonial_Date { get; set; }

        [Display(Name = "Testimonial")]
        [Required(ErrorMessage ="Testimonial Content Required")]
        public string Testimonial_Content { get; set; }

        [Display(Name = "Tenant SSN")]
        [DisplayFormat(DataFormatString = "{0:###-##-####}")]
        public Nullable<int> Tenant_SS { get; set; }

        public virtual Tenant Tenant { get; set; }
    }
}
